create table if not exists public.question_bank (
  id integer generated by default as identity primary key,
  question text not null,
  options text[] not null check (array_length(options, 1) = 4),
  correct_answer smallint not null check (correct_answer between 0 and 3),
  verse text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.question_bank enable row level security;

drop policy if exists "question_bank_select_public" on public.question_bank;
create policy "question_bank_select_public"
  on public.question_bank
  for select
  to anon, authenticated
  using (active = true);

create or replace function public.update_question_bank_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_question_bank_updated_at on public.question_bank;
create trigger trg_question_bank_updated_at
before update on public.question_bank
for each row execute function public.update_question_bank_updated_at();

insert into public.question_bank (id, question, options, correct_answer, verse, active)
values
  (1, 'Segun Colosenses 1:9, que es lo que Pablo no cesaba de hacer por los hermanos?', array['Visitar sus casas','Orar y pedir por ellos','Recaudar ofrendas','Escribirles cartas de reprension'], 1, 'Colosenses 1:9', true),
  (2, 'De que desea Pablo que seamos llenos, segun el texto de Colosenses?', array['De bienes materiales y salud','Del conocimiento de Su voluntad','De paciencia para las pruebas','De autoridad sobre los demas'], 1, 'Colosenses 1:9', true),
  (3, 'Que herramientas espirituales menciona el texto para alcanzar ese conocimiento?', array['Inteligencia logica y memoria','Sabiduria y astucia humana','Sabiduria e inteligencia espiritual','Estudio teologico y filosofia'], 2, 'Colosenses 1:9', true),
  (4, 'Cual es el proposito final de recibir esta sabiduria e inteligencia espiritual?', array['Ser reconocidos como lideres en la iglesia','Poder explicar misterios a los no creyentes','Andar como es digno del Senor, agradandole en todo','Evitar cualquier tipo de sufrimiento terrenal'], 2, 'Colosenses 1:10', true),
  (5, 'Que fruto se espera de un creyente que camina en la voluntad de Dios?', array['Exito profesional y financiero','Fruto en toda buena obra','Fama y reconocimiento publico','Perfeccion total sin errores'], 1, 'Colosenses 1:10', true),
  (6, 'Segun la reflexion de las fuentes, de donde proviene la sabiduria y el conocimiento?', array['Del esfuerzo intelectual propio','Es un regalo que viene de Dios por gracia','De la experiencia acumulada con los anos','De leer muchos libros de superacion personal'], 1, 'Romanos 11:36', true),
  (7, 'En el contexto de la oracion, que error solemos cometer segun el audio?', array['Orar demasiado tiempo','Orar solo por proteccion o cuando hay problemas dificiles','Orar con palabras muy sencillas','No pedir por nuestras necesidades fisicas'], 1, 'Efesios 6:18', true),
  (8, 'Que significa orar en todo tiempo segun la explicacion dada en la reunion?', array['Estar las 24 horas del dia de rodillas','No trabajar para dedicarse solo a la oracion','Tener a Dios presente en los pensamientos y actividades diarias','Orar unicamente dentro del templo'], 2, 'Efesios 6:18', true),
  (9, 'Segun el audio, que nos permite acercarnos a Dios con confianza?', array['Nuestras buenas acciones y meritos','Leer la Palabra para conocer quien es El','El tiempo que llevamos asistiendo a la iglesia','No haber cometido pecados graves recientemente'], 1, 'Romanos 10:17', true),
  (10, 'A que reino fuimos trasladados despues de estar en tinieblas?', array['Al reino de este mundo','Al reino de Su amado Hijo (Luz)','A un estado de confusion espiritual','Al paraiso terrenal recuperado'], 1, 'Colosenses 1:13', true),
  (11, 'En Mateo 24, que predijo Jesus sobre los edificios del templo?', array['Que serian remodelados y ampliados','Que permanecerian para siempre como senal','Que no quedaria piedra sobre piedra que no fuera derribada','Que serian el centro del gobierno mundial'], 2, 'Mateo 24:2', true),
  (12, 'Que pregunta especifica le hicieron los discipulos a Jesus en el Monte de los Olivos?', array['Como podian ser los mas importantes en el reino','Cuando serian estas cosas y que senal habria de Su venida','Como podian multiplicar los panes y los peces','Quien seria el traidor entre ellos'], 1, 'Mateo 24:3', true),
  (13, 'Cual es la primera advertencia que Jesus da sobre el fin de los tiempos?', array['Que preparen provisiones de comida','Que miren que nadie los engane','Que se refugien en las cuevas','Que no tengan miedo a las enfermedades'], 1, 'Mateo 24:4', true),
  (14, 'Segun Mateo 24, que eventos son considerados el principio de dolores?', array['El establecimiento de un gobierno global unico','Guerras, rumores de guerras, pestes, hambres y terremotos','La reconstruccion del templo de Jerusalen','La conversion masiva de todas las naciones'], 1, 'Mateo 24:6-8', true),
  (15, 'Que sucedera con el amor de muchos debido al aumento de la maldad?', array['Se fortalecera para resistir','Se enfriara','Se volvera solo hacia la familia','Desaparecera por completo de la tierra'], 1, 'Mateo 24:12', true),
  (16, 'Quien sera salvo segun Mateo 24:13?', array['El que tenga mas conocimiento teologico','El que nunca haya cometido un error','El que persevere hasta el fin','El que se esconda de las tribulaciones'], 2, 'Mateo 24:13', true),
  (17, 'Que requisito debe cumplirse antes de que venga el fin?', array['Que se descubran todos los secretos de la ciencia','Que el evangelio sea predicado en todo el mundo','Que haya paz total en la tierra','Que todos los seres humanos hablen el mismo idioma'], 1, 'Mateo 24:14', true),
  (18, 'Como describe Jesus Su venida para que no seamos enganados por falsos Cristos?', array['Como un secreto que solo pocos conoceran','Como el relampago que sale del oriente y se muestra al occidente','Como un hombre que aparecera caminando en el desierto','Como una voz que se escuchara solo en el interior de las casas'], 1, 'Mateo 24:27', true),
  (19, 'Que senales haran los falsos Cristos y profetas para intentar enganar a los escogidos?', array['Discursos muy elocuentes y politicos','Grandes senales y prodigios','Regalaran riquezas a sus seguidores','Prometeran salud fisica inmediata'], 1, 'Mateo 24:24', true),
  (20, 'Segun la reflexion sobre la senal del WiFi, que sucede cuando nos alejamos de Cristo?', array['Nuestra fe se vuelve mas independiente','La senal o fortaleza espiritual baja y somos mas propensos al pecado y al engano','No pasa nada, porque la salvacion no se pierde','Dios nos busca con mas intensidad automaticamente'], 1, 'Juan 15:5', true),
  (21, 'Que tipo de paz ofrece Jesus a diferencia de la paz del mundo?', array['Una paz basada en la ausencia de conflictos externos','Una paz que sobrepasa todo entendimiento, incluso en la tribulacion','Una paz que se consigue mediante la meditacion humana','Una paz que depende de tener estabilidad economica'], 1, 'Juan 14:27', true),
  (22, 'Segun las fuentes, por que es vital tener discernimiento espiritual hoy?', array['Para poder juzgar a los demas con justicia','Para no ser enganados por falsas doctrinas o falsos Cristos','Para saber como invertir mejor nuestro dinero','Para predecir la fecha exacta del fin del mundo'], 1, 'Mateo 24:4', true),
  (23, 'Que dice Romanos 8 citado en la reflexion sobre el amor de Cristo?', array['Que el pecado nos separa definitivamente de el','Que nada hambre, tribulacion, persecucion nos podra separar de su amor','Que solo los que no sufren estan en su amor','Que es un amor que debemos ganar con esfuerzo'], 1, 'Romanos 8:35-39', true),
  (24, 'Que actitud debemos tener ante las guerras y problemas globales segun Mateo 24:6?', array['Debemos entrar en panico y desesperacion','Debemos mirar que no nos turbemos, pues es necesario que suceda','Debemos protestar para detener el cumplimiento profetico','Debemos ignorar las noticias por completo'], 1, 'Mateo 24:6', true),
  (25, 'En la oracion final de la reunion, que se pide especificamente para los jovenes?', array['Que consigan los mejores empleos y lujos','Que no se afanen por lo material y busquen primero el reino de Dios','Que sean los mas populares en sus escuelas','Que viajen por todo el mundo predicando'], 1, 'Mateo 6:33', true),
  (26, 'Cual es el peligro de no conocer a Dios segun la reflexion del audio?', array['Simplemente no ir al cielo','Ser vulnerables a creerle a cualquier persona o doctrina','No poder tener amigos dentro de la iglesia','Tener una vida aburrida'], 1, 'Oseas 4:6', true),
  (27, 'Que profeta menciono la abominacion desoladora referida por Jesus?', array['Isaias','Jeremias','Daniel','Ezequiel'], 2, 'Mateo 24:15 / Daniel 9:27', true),
  (28, 'Por que seran acortados los dias de la gran tribulacion?', array['Por compasion a toda la humanidad en general','Por causa de los escogidos','Porque el enemigo se rendira antes de tiempo','Para que la tierra no sea destruida totalmente'], 1, 'Mateo 24:22', true),
  (29, 'Que frase resume la actitud de servicio hacia Dios mencionada en la reunion?', array['Hacer las cosas para ser vistos por los hombres','Hacerlo todo de corazon como para el Senor y no para los hombres','Trabajar solo cuando nos sentimos motivados emocionalmente','Buscar el beneficio personal a traves del servicio'], 1, 'Colosenses 3:23', true),
  (30, 'Cual es la verdad central sobre nuestra salvacion y conocimiento segun las fuentes?', array['Todo es por nuestro esfuerzo y dedicacion','Todo es de El, por medio de El y para El por gracia','Depende de cuantos versiculos memoricemos','Es un premio que Dios da a los que nunca fallan'], 1, 'Romanos 11:36', true)
on conflict (id) do update set
  question = excluded.question,
  options = excluded.options,
  correct_answer = excluded.correct_answer,
  verse = excluded.verse,
  active = excluded.active,
  updated_at = now();

select setval(pg_get_serial_sequence('public.question_bank', 'id'), 30, true);
