export type EventoItem = {
  id: string;
  fecha: string;
  title: string;
  subject: string;
  teacher: string;
  startTime: string;
  endTime: string;
  avatarUrl?: string | null;
  actionHref?: string | null;
  summaryHref?: string | null;
  readingHref?: string | null;
  tags?: string[];
};

export type EventoDbRow = {
  id?: string | number;
  fecha_evento?: string;
  fecha?: string;
  date?: string;
  dia?: string;
  day?: string;
  title?: string;
  titulo?: string;
  nombre?: string;
  subject?: string;
  materia?: string;
  tema?: string;
  teacher?: string;
  maestro?: string;
  profesor?: string;
  start_at?: string;
  end_at?: string;
  start_time?: string;
  hora_inicio?: string;
  inicio?: string;
  end_time?: string;
  hora_fin?: string;
  fin?: string;
  avatar_url?: string | null;
  cover_image_url?: string | null;
  live_link?: string | null;
  reading_link?: string | null;
  lectura_link?: string | null;
  reading_url?: string | null;
  enlace_lectura?: string | null;
  url_lectura?: string | null;
  link_lectura?: string | null;
  tags?: string[] | null;
  etiquetas?: string[] | null;
  published?: boolean | null;
};
